#配置文件示例：
#1ll73hur1bhm:                          # CDKey内容
#  command: 'eco give {player} 100 '    # 使用CDK后要执行的指令
#  op: true                             # 是否以OP（控制台）身份执行指令
# @！插件文件夹中的 Log.yml 为CDK使用记录，将会记录使用CDK的玩家以及使用时间！
# @！插件文件夹中的 Export.yml 为CDK导出列表！
# @！该插件代码提供者为EnRon233
# @！推荐发卡平台https://zoufk.com
# @！为商户谋福利，为买家供便利
